% Auto-generated by cameraCalibrator app on 12-Feb-2022
%-------------------------------------------------------


% Define images to process
imageFileNames = {'F:\Computer_Vision_and_Pattern_Recognition\CW1\FD10.JPG',...
    'F:\Computer_Vision_and_Pattern_Recognition\CW1\FD11.JPG',...
    'F:\Computer_Vision_and_Pattern_Recognition\CW1\FD12.JPG',...
    'F:\Computer_Vision_and_Pattern_Recognition\CW1\FD13.JPG',...
    'F:\Computer_Vision_and_Pattern_Recognition\CW1\FD14.JPG',...
    'F:\Computer_Vision_and_Pattern_Recognition\CW1\FD15.JPG',...
    'F:\Computer_Vision_and_Pattern_Recognition\CW1\FD16.JPG',...
    'F:\Computer_Vision_and_Pattern_Recognition\CW1\FD17.JPG',...
    'F:\Computer_Vision_and_Pattern_Recognition\CW1\FD18.JPG',...
    };
% Detect checkerboards in images
[imagePoints, boardSize, imagesUsed] = detectCheckerboardPoints(imageFileNames);
imageFileNames = imageFileNames(imagesUsed);

% Read the first image to obtain image size
originalImage = imread(imageFileNames{1});
[mrows, ncols, ~] = size(originalImage);

% Generate world coordinates of the corners of the squares
squareSize = 22;  % in units of 'millimeters'
worldPoints = generateCheckerboardPoints(boardSize, squareSize);

% Calibrate the camera
[iPhone11Cam, imagesUsed, iPhone11CamErrors] = estimateCameraParameters(imagePoints, worldPoints, ...
    'EstimateSkew', true, 'EstimateTangentialDistortion', true, ...
    'NumRadialDistortionCoefficients', 2, 'WorldUnits', 'millimeters', ...
    'InitialIntrinsicMatrix', [], 'InitialRadialDistortion', [], ...
    'ImageSize', [mrows, ncols]);

% View reprojection errors
h1=figure; showReprojectionErrors(iPhone11Cam);

% Visualize pattern locations
h2=figure; showExtrinsics(iPhone11Cam, 'CameraCentric');

% Display parameter estimation errors
displayErrors(iPhone11CamErrors, iPhone11Cam);

% For example, you can use the calibration data to remove effects of lens distortion.
undistortedImage = undistortImage(originalImage, iPhone11Cam);

% See additional examples of how to use the calibration data.  At the prompt type:
% showdemo('MeasuringPlanarObjectsExample')
% showdemo('StructureFromMotionExample')
